"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const ukrainianMessages = {
    ra: {
        action: {
            add_filter: 'Додати фільтр',
            add: 'Додати',
            back: 'Повернутися назад',
            bulk_actions: '%{smart_count} обрано',
            cancel: 'Відмінити',
            clear_input_value: 'Очистити',
            clone: 'Дублювати',
            confirm: 'Підтвердити',
            create: 'Створити',
            create_item: 'Створити %{item}',
            delete: 'Видалити',
            edit: 'Редагувати',
            export: 'Експортувати',
            list: 'Перелік',
            refresh: 'Оновити',
            remove_filter: 'Прибрати фільтр',
            remove: 'Видалити',
            save: 'Зберегти',
            search: 'Пошук',
            select_all: 'Обрати всі',
            select_row: 'Обрати цей рядок',
            show: 'Перегляд',
            sort: 'Сортувати',
            undo: 'Скасувати',
            unselect: 'Зняти обрання',
            expand: 'Розкрити',
            close: 'Закрити',
            open_menu: 'Меню',
            close_menu: 'Закрити меню',
            update: 'Оновити',
            move_up: 'Вгору',
            move_down: 'Вниз',
        },
        boolean: {
            true: 'Так',
            false: 'Ні',
            null: ' '
        },
        page: {
            create: 'Створити %{name}',
            dashboard: 'Дашборд',
            edit: '%{name} #%{id}',
            error: 'Щось пішло не так',
            list: '%{name}',
            loading: 'Завантаження',
            not_found: 'Не знайдено',
            show: '%{name} #%{id}',
            empty: 'Ще немає %{name}.',
            invite: 'Бажаєте додати?',
        },
        input: {
            file: {
                upload_several: 'Перетягніть файли сюди, або натисніть для вибору.',
                upload_single: 'Перетягніть файл сюди, або натисніть для вибору.',
            },
            image: {
                upload_several: 'Перетягніть зображення сюди, або натисніть для вибору.',
                upload_single: 'Перетягніть зображення сюди, або натисніть для вибору.',
            },
            references: {
                all_missing: 'Неможливо знайти дані посилань.',
                many_missing: "Щонайменьше одне з пов'язаних посилань більше не доступно.",
                single_missing: "Пов'язане посилання більше не доступно.",
            },
            password: {
                toggle_visible: 'Сховати пароль',
                toggle_hidden: 'Показати пароль',
            },
        },
        message: {
            about: 'Довідка',
            are_you_sure: 'Ви впевнені?',
            bulk_delete_content: 'Ви дійсно хочете видалити це %{name}? |||| Ви впевнені що хочете видалити ці %{smart_count} %{name}?',
            bulk_delete_title: 'Видалити %{name} |||| Видалити %{smart_count} %{name} елементів',
            bulk_update_content: 'Ви дійсно хочете оновити це %{name}? |||| Ви впевнені що хочете оновити ці %{smart_count} %{name}?',
            bulk_update_title: 'Оновити %{name} |||| Оновити %{smart_count} %{name}',
            delete_content: 'Ви впевнені що хочете видалити цей елемент?',
            delete_title: 'Видалити %{name} #%{id}',
            details: 'Деталі',
            error: "Виникла помилка на стороні клієнта і ваш запит не був завершений.",
            invalid_form: 'Форма недійсна. Перевірте помилки',
            loading: 'Сторінка завантажується, хвилинку будь ласка',
            no: 'Ні',
            not_found: 'Ви набрали невірний URL-адресу, або перейшли за хибним посиланням.',
            yes: 'Так',
            unsaved_changes: "Деякі зміни не були збережені.Ви впевнені що хочете проігнорувати їх?",
        },
        navigation: {
            no_results: 'Результатів не знайдено',
            no_more_results: 'Номер сторінки %{page} знаходиться за межами кордонів. Спробуйте попередню сторінку.',
            page_out_of_boundaries: 'Сторінка %{page} поза межами',
            page_out_from_end: 'Неможливо переміститися далі останньої сторінки',
            page_out_from_begin: 'Номер сторінки не може бути менше 1',
            page_range_info: '%{offsetBegin}-%{offsetEnd} із %{total}',
            page_rows_per_page: 'Рядків на сторінці:',
            next: 'Наступна',
            prev: 'Попередня',
            skip_nav: 'Skip to content',
        },
        sort: {
            sort_by: 'Сортувати за %{field} %{order}',
            ASC: 'висхідний',
            DESC: 'низхідний',
        },
        auth: {
            auth_check_error: 'Щоб продовжити, будь ласка залогінтесь',
            user_menu: 'Профіль',
            username: "Ім'я користувача",
            password: 'Пароль',
            sign_in: 'Ввійти',
            sign_in_error: 'Помилка аутентифікації, спробуйте знову',
            logout: 'Вийти',
        },
        notification: {
            updated: 'Елемент оновлено |||| %{smart_count} елемент оновлено',
            created: 'Елемент створений',
            deleted: 'Елемент видалений |||| %{smart_count} елемент видалено',
            bad_item: 'Хибний елемент',
            item_doesnt_exist: 'Елемент не існує',
            http_error: 'Помилка сервера',
            data_provider_error: 'Помилка в dataProvider. Перевірте деталі в консолі.',
            i18n_error: 'Не вдалося завантажити переклад для вибраної мови',
            canceled: 'Дія відмінена',
            logged_out: 'Ваша логін-сессія завершена, будь ласка залогінтесь знову.',
            not_authorized: "Немає доступу до цього ресурсу.",
        },
        validation: {
            required: "Обов'язково для заповнення",
            minLength: 'Мінімальна кількість символів %{min}',
            maxLength: 'Максимальна кількість символів %{max}',
            minValue: 'Мінімальне значення %{min}',
            maxValue: 'Значення може бути %{max} або менше',
            number: 'Повинна бути цифра',
            email: 'Хибний email',
            oneOf: 'Повинен бути одним з: %{options}',
            regex: 'Повинен відповідати певним форматом (регулярний вираз): %{pattern}',
        },
    },
};
exports.default = ukrainianMessages;
